apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fcc.fullname" . }}-secrets
type: Opaque
stringData:
  PROXY_AUTH_TOKEN: {{ .Values.secrets.PROXY_AUTH_TOKEN | default "" | quote }}
  FCC_ADMIN_API_TOKEN: {{ .Values.secrets.FCC_ADMIN_API_TOKEN | default "" | quote }}
  FCC_ADMIN_IP_ALLOWLIST: {{ .Values.secrets.FCC_ADMIN_IP_ALLOWLIST | default "" | quote }}
